### ISSUE TITLE
[ TP6 ] [ Cenário 1 ] Requisitos Funcionais e Não Funcionais

### ISSUE THREAD

**Issue by SouAline** [SouAline/pet-friendly#1]
Critérios de aceite desta tarefa
-
- [x] Escrever os requisitos funcionais
- [x] Escrever os requisitos não funcionais
- [x] Acrescentar print do requisitos   
- [x] Acrescentar id, descrição e prioridade

Requisitos
=

![Captura de Tela (48)](https://user-images.githubusercontent.com/80184523/156456846-b0c00871-dd88-4fac-866c-2777ddb4cd44.png)

Documentação
=
Você encontra os requisitos funcionais [aqui](https://www.figma.com/file/6YLTkHSc5F3Sc0DV1ubFpG/Projeto-de-bloco?node-id=0%3A1)

**Comment by SouAline** [comment]
Review ok

**Comment by marcdevrenan** [comment]
Review ok

**Comment by cahcastroc** [comment]
Review ok
