### ISSUE TITLE
[ TP6 ] [ Cenário 2 ] [ Requisito não funcional ] User histories  

### ISSUE THREAD

**Issue by SouAline** [SouAline/pet-friendly#11]
Critérios de aceite desta tarefa
- [x] Escrever a história de usuário
- [x] Escrever no titulo abaixo qual o requisito funcional a qual esta atrelada   
- [x] Escrever os critérios de aceite da user histories

User Histories RNF-002
=
Eu como tutor de pet e cadastrado no aplicativo quero ser capaz de pesquisar, visualizar feedbacks e avaliar estabelecimentos pet-friendly.

Critérios de aceite
-
- Campo para avaliação contendo as opções de:
    - Upvote
    - Downvote
    - Feedback

- Ordenar pesquisa por:
    - Upvote
    - Downvote

Documentação
-
Você encontra a documentação do projeto  [aqui](https://www.figma.com/file/6YLTkHSc5F3Sc0DV1ubFpG/Projeto-de-bloco?node-id=0%3A1)

**Comment by cahcastroc** [comment]
Review ok

**Comment by jupazpinheiro** [comment]
Review ok
