### ISSUE TITLE
[ TP6 ] [ Cenário 2 ]  [ Requisito funcional ] User histories 

### ISSUE THREAD

**Issue by SouAline** [SouAline/pet-friendly#12]
Critérios de aceite desta tarefa
- [x] Escrever a história de usuário
- [x] Escrever no titulo abaixo qual o requisito funcional a qual esta atrelada   
- [x] Escrever os critérios de aceite da user histories

User Histories RF-002
=
Eu como tutor de pet e cadastrado no aplicativo, quero ser capaz de pesquisar estabelecimentos e filtrá-los por tipo e porte de animais permitidos.

Critérios de aceite
-
- Filtro de pesquisa por:
    - Tipo de animal
    - Porte do animal

- Ordenar pesquisa por:
    - Mais frequentes
    - Porte crescente
    - Porte decrescente

Documentação
-
Você encontra a documentação do projeto  [aqui](https://www.figma.com/file/6YLTkHSc5F3Sc0DV1ubFpG/Projeto-de-bloco?node-id=0%3A1)

**Comment by SouAline** [comment]
Review ok

**Comment by marcdevrenan** [comment]
Review ok

**Comment by cahcastroc** [comment]
Review ok

**Comment by jupazpinheiro** [comment]
Review ok
