### ISSUE TITLE
[ TP6 ] [ Cenário 1 ] [ Requisito funcional ]  User histories   

### ISSUE THREAD

**Issue by SouAline** [SouAline/pet-friendly#4]
Critérios de aceite desta tarefa
- [x] Escrever a história de usuário
- [x] Escrever no titulo abaixo qual o requisito funcional a qual esta atrelada   
- [x] Escrever os critérios de aceite da user histories

User Histories RF-002 
=
Eu como tutora de pet quero consultar da minha cidade, quais hotéis que seguem a cultura pet-friendly para me hospedar no Rio De Janeiro com meu cachorro.

Critérios de aceite
-
- Filtro de pesquisa por categorias como:
     - Hotéis
     - Praças
     - Restaurantes

- Busca por avaliações como:
     - Mais bem avaliados
     - Mais próximos

Documentação
Você encontra a documentação do nosso projeto [aqui](https://www.figma.com/file/6YLTkHSc5F3Sc0DV1ubFpG/Projeto-de-bloco?node-id=28%3A277)

**Comment by SouAline** [comment]
Review ok

**Comment by marcdevrenan** [comment]
Review ok

**Comment by jupazpinheiro** [comment]
review ok
