### ISSUE TITLE
[ TP6 ] Cenário 2

### ISSUE THREAD

**Issue by SouAline** [SouAline/pet-friendly#6]
Critérios de aceite
-
- [x] Escrever cena
- [x] Escrever atores envolvidos
- [x] Escrever Ação

Cena Representada
=
Avaliação da experiência a partir de uma empresa encontrada no aplicativo MiAuT.   

Atores envolvidos
-
Tutores cadastrados no aplicativo   

Ação
-
Tutor cadastrado no aplicativo descobriu novos lugares em que pode levar seu pet. Ele deseja avaliar as empresas para manter um histórico de que lugares ele conseguiu alcançar a experiência desejada.    

Documentação
-
Você encontra a documentação do nosso projeto [aqui](https://www.figma.com/file/6YLTkHSc5F3Sc0DV1ubFpG/Projeto-de-bloco?node-id=28%3A277)

**Comment by SouAline** [comment]
Review ok

**Comment by marcdevrenan** [comment]
Review ok

**Comment by cahcastroc** [comment]
Review ok
