### ISSUE TITLE
[ TP6 ] [ Cenário 2 ] Requisitos Funcionais

### ISSUE THREAD

**Issue by SouAline** [SouAline/pet-friendly#8]
Critérios de aceite desta tarefa
-
- [x] Escrever os requisitos funcionais
- [x] Acrescentar print do requisitos   
- [x] Acrescentar id, descrição e prioridade
  

Requisitos
-
![Captura de Tela (47)](https://user-images.githubusercontent.com/80184523/156458089-6ca4fe75-d58b-4993-8516-bceea9ef6b04.png)

Documentação
-
Você encontra a documentação do nosso projeto [aqui](https://www.figma.com/file/6YLTkHSc5F3Sc0DV1ubFpG/Projeto-de-bloco?node-id=28%3A277)

**Comment by SouAline** [comment]
Review ok

**Comment by marcdevrenan** [comment]
Review ok

**Comment by cahcastroc** [comment]
Review ok
